language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: UnMWIJyaV+lXXjxDXlkmJ+JqKBsQWxEmf1FD/sxlSuDmYndINUrnJkbvPm3Ih273jfb7XebcQG1xQl7922IZcvfWiiL9rhR2pWfBDv2WL8IUJ0SPQQVn2tHojwLWm86PnHHSheB1HKrys3xljohyNjty3hYhxH5+nwQVwXxsvaA8FuyaL5VPuEWi6kpuNWmtGBVo07q8OvMUr08uXW+0zWzs8fPMXj+BRRz0cjynrFEAGkb8PIWwkh6STHI7hWKmBbr3c4IRMmNHS3wicdB8OGbJnoakvuIU+GsakBlp7sbJdqtxzeGHSqph+R60p2v/q6AvRd45GojDhMlsxRFJD6X/yM11bfSSlZYytDbp07zOstHVb/ryzhxGALueF8VjUgC/PHIblTm3jVbFbTuZKom4/47z+JAXKqrTJeUTmCMf8DI70pdJ3PJeJOjc2E88zqXBlM9v3bVIlHzE2Fxl29yKqtN2m2bXaFUzGKPwWKBekjNI5qXwyJoQM4EW3JBv54Xcoybt2V4Yqce77EDw+xMLwHgQPAZtOWQg7BPTXv3hArEUsCa0P314uovCchIYbtE3+htzLx4a+87i2UDreCgvgwSFlL2GcQs6zfgMQ2JNI9mP/lc4880/7JGg7DCen7vfQ21vLA8NzowiAk5AmCgq4XP3wucvM2nNmvB8GZA=
  app: saywhat-speech-api
  on:
    repo: imagineLife/say-what-api
