version: '3.8'
services:
  mongobox:
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: test_pw
  api:
    depends_on:
      - mongobox
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: ["npm", "run", "start:docker-dev"]
    ports:
      - 3000:3000